services:
  - type: web
    name: sumaa-pro
    runtime: python
    plan: starter
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: DATA_DIR
        value: /var/data
    disk:
      name: sumaa-data
      mountPath: /var/data
      sizeGB: 1
